service: express-user-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DYNAMO_DB_TABLE: USERAPI
  iamRoleStatements:
    - Effect: Allow
      Action:
        # - dynamodb:*
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource: 
        # "*"
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMO_DB_TABLE}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMO_DB_TABLE}/index/GSI1

functions:
  checkAPI:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /
          method: get

  createUser:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /users
          method: post
  
  getAllUsers:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /users
          method: get

  getUserById:
    handler: src/handler.handler
    events:
      - httpApi: 
          path: /users/{id}
          method: get

  getUserByEmail:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /users/by-email
          method: get

  updateUser:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /users/{id}
          method: put

  deleteUser:
    handler: src/handler.handler
    events:
      - httpApi: 
          path: /users/{id}
          method: delete


  # api:
    # handler: src/handler.handler
    # events:
      # - httpApi: '*'

plugins:
  - serverless-webpack
  # []

custom:
  webpack:
    webpackConfig: ./webpack.config.cjs
    includeModules: true
  build:
    esbuild: false

resources:
  Resources:
    USERAPI:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: USERAPI
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
